# Agenda
* Numpy
* Pandas
* Lab


# Introduction


## Create a new notebook for your code-along:

From our submission directory, type:
    
    jupyter notebook

From the IPython Dashboard, open a new notebook.
Change the title to: "Numpy and Pandas"

# Introduction to Numpy

* Overview
* ndarray
* Indexing and Slicing

More info: [http://wiki.scipy.org/Tentative_NumPy_Tutorial](http://wiki.scipy.org/Tentative_NumPy_Tutorial)


## Numpy Overview

* Why Python for Data? Numpy brings *decades* of C math into Python!
* Numpy provides a wrapper for extensive C/C++/Fortran codebases, used for data analysis functionality
* NDAarray allows easy vectorized math and broadcasting (i.e. functions for vector elements of different shapes)

In [1]:
import numpy as np

### Creating ndarrays

An array object represents a multidimensional, homogeneous array of fixed-size items. 

In [2]:
np.zeros(3)

array([0., 0., 0.])

In [3]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
np.random.randint(1, 20, 5)

array([11, 11,  5,  9,  9])

In [9]:
r = np.random.randint(1, 20, 6)

In [12]:
np.reshape?

In [13]:
np.reshape(r, (2, 3))

array([[16,  7, 15],
       [16, 10,  1]])

In [14]:
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [16]:
## Arithmetic in arrays is element wise

In [17]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [18]:
c = a-b
c

array([20, 29, 38, 47])

In [19]:
b**2

array([0, 1, 4, 9])

### Problem

Use the documentation for the `np.random` methods to create a DataFrame that contains four columns, one with uniformly distributed random numbers, one with normally distributed random functions, and one with a hypergeometric distribution.  Plot each indivudually as a histogram.

## Indexing, Slicing and Iterating

In [20]:
# one-dimensional arrays work like lists:
a = np.arange(10)**2

In [21]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [22]:
a[2:5]

array([ 4,  9, 16])

In [ ]:
# Multidimensional arrays use tuples with commas for indexing
# with (row,column) conventions beginning, as always in Python, from 0

In [23]:
b = np.random.randint(1,100,(4,4))

In [26]:
b

array([[15, 73, 37, 91],
       [44, 93, 18, 19],
       [ 6, 22, 63,  3],
       [46, 96, 73, 20]])

In [27]:
b[0:3,1],b[:,1]

(array([73, 93, 22]), array([73, 93, 22, 96]))

In [28]:
b[1:3,:]

array([[44, 93, 18, 19],
       [ 6, 22, 63,  3]])

# Introduction to Pandas

* Object Creation
* Viewing data
* Selection
* Missing data
* Grouping
* Reshaping
* Time series
* Plotting
* i/o
 

_pandas.pydata.org_

## Pandas Overview

_Source: [pandas.pydata.org](http://pandas.pydata.org/pandas-docs/stable/10min.html)_

In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [30]:
tips = sns.load_dataset('tips')

In [31]:
type(tips)

pandas.core.frame.DataFrame

In [32]:
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [33]:
tips.head(8)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4

In [34]:
tips.T

0       1       2       3       4       5       6       7    \
total_bill   16.99   10.34   21.01   23.68   24.59   25.29    8.77   26.88   
tip           1.01    1.66     3.5    3.31    3.61    4.71       2    3.12   
sex         Female    Male    Male    Male  Female    Male    Male    Male   
smoker          No      No      No      No      No      No      No      No   
day            Sun     Sun     Sun     Sun     Sun     Sun     Sun     Sun   
time        Dinner  Dinner  Dinner  Dinner  Dinner  Dinner  Dinner  Dinner   
size             2       3       3       2       4       4       2       4   

               8       9     ...       234     235     236     237     238  \
total_bill   15.04   14.78   ...     15.53   10.07    12.6   32.83   35.83   
tip           1.96    3.23   ...         3    1.25       1    1.17    4.67   
sex           Male    Male   ...      Male    Male    Male    Male  Female   
smoker          No      No   ...       Yes      No     Yes     Yes      No   
day            Sun     Sun   ...       Sat     Sat     Sat     Sat     Sat   
time        Dinner  Dinner   ...    Dinner  Dinner  Dinner  Dinner  Dinner   
size             2       2   ...         2       2       2       2       3   

               239     240     241     242     243  
total_bill   29.03   27.18   22.67   17.82   18.78  
tip           5.92       2       2    1.75       3  
sex           Male  Female    Male    Male  Female  
smoker          No     Yes     Yes      No      No  
day            Sat     Sat     Sat     Sat    Thur  
time        Dinner  Dinner  Dinner  Dinner  Dinner  
size             3       2       2       2       2  

[7 rows x 244 columns]

In [35]:
# With specific dtypes
tips.dtypes

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

#### Viewing Data

In [36]:
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [37]:
tips.tail()

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [38]:
tips.index

RangeIndex(start=0, stop=244, step=1)

In [39]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [41]:
tips.sort_values(by='tip')

total_bill    tip     sex smoker   day    time  size
67         3.07   1.00  Female    Yes   Sat  Dinner     1
236       12.60   1.00    Male    Yes   Sat  Dinner     2
92         5.75   1.00  Female    Yes   Fri  Dinner     2
111        7.25   1.00  Female     No   Sat  Dinner     1
0         16.99   1.01  Female     No   Sun  Dinner     2
215       12.90   1.10  Female    Yes   Sat  Dinner     2
237       32.83   1.17    Male    Yes   Sat  Dinner     2
235       10.07   1.25    Male     No   Sat  Dinner     2
75        10.51   1.25    Male     No   Sat  Dinner     2
135        8.51   1.25  Female     No  Thur   Lunch     2
43         9.68   1.32    Male     No   Sun  Dinner     2
146       18.64   1.36  Female     No  Thur   Lunch     3
218        7.74   1.44    Male    Yes   Sat  Dinner     2
195        7.56   1.44    Male     No  Thur   Lunch     2
30         9.55   1.45    Male     No   Sat  Dinner     2
233       10.77   1.47    Male     No   Sat  Dinner     2
126        8.52   1.48    Male     No  Thur   Lunch     2
190       15.69   1.50    Male    Yes   Sun  Dinner     2
57        26.41   1.50  Female     No   Sat  Dinner     2
97        12.03   1.50    Male    Yes   Fri  Dinner     2
99        12.46   1.50    Male     No   Fri  Dinner     2
117       10.65   1.50  Female     No  Thur   Lunch     2
132       11.17   1.50  Female     No  Thur   Lunch     2
217       11.59   1.50    Male    Yes   Sat  Dinner     2
145        8.35   1.50  Female     No  Thur   Lunch     2
130       19.08   1.50    Male     No  Thur   Lunch     2
53         9.94   1.56    Male     No   Sun  Dinner     2
12        15.42   1.57    Male     No   Sun  Dinner     2
224       13.42   1.58    Male    Yes   Fri   Lunch     2
168       10.59   1.61  Female    Yes   Sat  Dinner     2
..          ...    ...     ...    ...   ...     ...   ...
5         25.29   4.71    Male     No   Sun  Dinner     4
95        40.17   4.73    Male    Yes   Fri  Dinner     4
46        22.23   5.00    Male     No   Sun  Dinner     2
39        31.27   5.00    Male     No   Sat  Dinner     3
142       41.19   5.00    Male     No  Thur   Lunch     5
143       27.05   5.00  Female     No  Thur   Lunch     6
156       48.17   5.00    Male     No   Sun  Dinner     6
185       20.69   5.00    Male     No   Sun  Dinner     5
11        35.26   5.00  Female     No   Sun  Dinner     4
83        32.68   5.00    Male    Yes  Thur   Lunch     2
197       43.11   5.00  Female    Yes  Thur   Lunch     4
73        25.28   5.00  Female    Yes   Sat  Dinner     2
116       29.93   5.07    Male     No   Sun  Dinner     4
155       29.85   5.14  Female     No   Sun  Dinner     5
172        7.25   5.15    Male    Yes   Sun  Dinner     2
211       25.89   5.16    Male    Yes   Sat  Dinner     4
85        34.83   5.17  Female     No  Thur   Lunch     4
52        34.81   5.20  Female     No   Sun  Dinner     4
44        30.40   5.60    Male     No   Sun  Dinner     4
181       23.33   5.65    Male    Yes   Sun  Dinner     2
88        24.71   5.85    Male     No  Thur   Lunch     2
239       29.03   5.92    Male     No   Sat  Dinner     3
47        32.40   6.00    Male     No   Sun  Dinner     4
183       23.17   6.50    Male    Yes   Sun  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3
141       34.30   6.70    Male     No  Thur   Lunch     6
59        48.27   6.73    Male     No   Sat  Dinner     4
23        39.42   7.58    Male     No   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
170       50.81  10.00    Male    Yes   Sat  Dinner     3

[244 rows x 7 columns]

In [42]:
tips.sort_values?

### Selection

In [43]:
tips[['tip', 'sex']]

tip     sex
0    1.01  Female
1    1.66    Male
2    3.50    Male
3    3.31    Male
4    3.61  Female
5    4.71    Male
6    2.00    Male
7    3.12    Male
8    1.96    Male
9    3.23    Male
10   1.71    Male
11   5.00  Female
12   1.57    Male
13   3.00    Male
14   3.02  Female
15   3.92    Male
16   1.67  Female
17   3.71    Male
18   3.50  Female
19   3.35    Male
20   4.08    Male
21   2.75  Female
22   2.23  Female
23   7.58    Male
24   3.18    Male
25   2.34    Male
26   2.00    Male
27   2.00    Male
28   4.30    Male
29   3.00  Female
..    ...     ...
214  6.50  Female
215  1.10  Female
216  3.00    Male
217  1.50    Male
218  1.44    Male
219  3.09  Female
220  2.20    Male
221  3.48  Female
222  1.92    Male
223  3.00  Female
224  1.58    Male
225  2.50  Female
226  2.00  Female
227  3.00    Male
228  2.72    Male
229  2.88  Female
230  2.00    Male
231  3.00    Male
232  3.39    Male
233  1.47    Male
234  3.00    Male
235  1.25    Male
236  1.00    Male
237  1.17    Male
238  4.67  Female
239  5.92    Male
240  2.00  Female
241  2.00    Male
242  1.75    Male
243  3.00  Female

[244 rows x 2 columns]

In [44]:
tips[0:3]

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

In [45]:
# By label
tips.loc[[0], 'smoker']

0    No
Name: smoker, dtype: category
Categories (2, object): [Yes, No]

In [46]:
# multi-axis by label
tips.loc[:,['day', 'time']]

day    time
0     Sun  Dinner
1     Sun  Dinner
2     Sun  Dinner
3     Sun  Dinner
4     Sun  Dinner
5     Sun  Dinner
6     Sun  Dinner
7     Sun  Dinner
8     Sun  Dinner
9     Sun  Dinner
10    Sun  Dinner
11    Sun  Dinner
12    Sun  Dinner
13    Sun  Dinner
14    Sun  Dinner
15    Sun  Dinner
16    Sun  Dinner
17    Sun  Dinner
18    Sun  Dinner
19    Sat  Dinner
20    Sat  Dinner
21    Sat  Dinner
22    Sat  Dinner
23    Sat  Dinner
24    Sat  Dinner
25    Sat  Dinner
26    Sat  Dinner
27    Sat  Dinner
28    Sat  Dinner
29    Sat  Dinner
..    ...     ...
214   Sat  Dinner
215   Sat  Dinner
216   Sat  Dinner
217   Sat  Dinner
218   Sat  Dinner
219   Sat  Dinner
220   Fri   Lunch
221   Fri   Lunch
222   Fri   Lunch
223   Fri   Lunch
224   Fri   Lunch
225   Fri   Lunch
226   Fri   Lunch
227   Sat  Dinner
228   Sat  Dinner
229   Sat  Dinner
230   Sat  Dinner
231   Sat  Dinner
232   Sat  Dinner
233   Sat  Dinner
234   Sat  Dinner
235   Sat  Dinner
236   Sat  Dinner
237   Sat  Dinner
238   Sat  Dinner
239   Sat  Dinner
240   Sat  Dinner
241   Sat  Dinner
242   Sat  Dinner
243  Thur  Dinner

[244 rows x 2 columns]

In [47]:
# iloc provides integer locations similar to np style
tips.iloc[3:]

total_bill   tip     sex smoker   day    time  size
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
6          8.77  2.00    Male     No   Sun  Dinner     2
7         26.88  3.12    Male     No   Sun  Dinner     4
8         15.04  1.96    Male     No   Sun  Dinner     2
9         14.78  3.23    Male     No   Sun  Dinner     2
10        10.27  1.71    Male     No   Sun  Dinner     2
11        35.26  5.00  Female     No   Sun  Dinner     4
12        15.42  1.57    Male     No   Sun  Dinner     2
13        18.43  3.00    Male     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
15        21.58  3.92    Male     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
17        16.29  3.71    Male     No   Sun  Dinner     3
18        16.97  3.50  Female     No   Sun  Dinner     3
19        20.65  3.35    Male     No   Sat  Dinner     3
20        17.92  4.08    Male     No   Sat  Dinner     2
21        20.29  2.75  Female     No   Sat  Dinner     2
22        15.77  2.23  Female     No   Sat  Dinner     2
23        39.42  7.58    Male     No   Sat  Dinner     4
24        19.82  3.18    Male     No   Sat  Dinner     2
25        17.81  2.34    Male     No   Sat  Dinner     4
26        13.37  2.00    Male     No   Sat  Dinner     2
27        12.69  2.00    Male     No   Sat  Dinner     2
28        21.70  4.30    Male     No   Sat  Dinner     2
29        19.65  3.00  Female     No   Sat  Dinner     2
30         9.55  1.45    Male     No   Sat  Dinner     2
31        18.35  2.50    Male     No   Sat  Dinner     4
32        15.06  3.00  Female     No   Sat  Dinner     2
..          ...   ...     ...    ...   ...     ...   ...
214       28.17  6.50  Female    Yes   Sat  Dinner     3
215       12.90  1.10  Female    Yes   Sat  Dinner     2
216       28.15  3.00    Male    Yes   Sat  Dinner     5
217       11.59  1.50    Male    Yes   Sat  Dinner     2
218        7.74  1.44    Male    Yes   Sat  Dinner     2
219       30.14  3.09  Female    Yes   Sat  Dinner     4
220       12.16  2.20    Male    Yes   Fri   Lunch     2
221       13.42  3.48  Female    Yes   Fri   Lunch     2
222        8.58  1.92    Male    Yes   Fri   Lunch     1
223       15.98  3.00  Female     No   Fri   Lunch     3
224       13.42  1.58    Male    Yes   Fri   Lunch     2
225       16.27  2.50  Female    Yes   Fri   Lunch     2
226       10.09  2.00  Female    Yes   Fri   Lunch     2
227       20.45  3.00    Male     No   Sat  Dinner     4
228       13.28  2.72    Male     No   Sat  Dinner     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
230       24.01  2.00    Male    Yes   Sat  Dinner     4
231       15.69  3.00    Male    Yes   Sat  Dinner     3
232       11.61  3.39    Male     No   Sat  Dinner     2
233       10.77  1.47    Male     No   Sat  Dinner     2
234       15.53  3.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[241 rows x 7 columns]

### Boolean Indexing

In [53]:
tips[(tips.tip > 5) & (tips.tip < 10)] # Basically a 'where' operation

total_bill   tip     sex smoker   day    time  size
23        39.42  7.58    Male     No   Sat  Dinner     4
44        30.40  5.60    Male     No   Sun  Dinner     4
47        32.40  6.00    Male     No   Sun  Dinner     4
52        34.81  5.20  Female     No   Sun  Dinner     4
59        48.27  6.73    Male     No   Sat  Dinner     4
85        34.83  5.17  Female     No  Thur   Lunch     4
88        24.71  5.85    Male     No  Thur   Lunch     2
116       29.93  5.07    Male     No   Sun  Dinner     4
141       34.30  6.70    Male     No  Thur   Lunch     6
155       29.85  5.14  Female     No   Sun  Dinner     5
172        7.25  5.15    Male    Yes   Sun  Dinner     2
181       23.33  5.65    Male    Yes   Sun  Dinner     2
183       23.17  6.50    Male    Yes   Sun  Dinner     4
211       25.89  5.16    Male    Yes   Sat  Dinner     4
212       48.33  9.00    Male     No   Sat  Dinner     4
214       28.17  6.50  Female    Yes   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3

### Setting

In [54]:
tips_copy = tips.copy() # Without "copy" it would act on the dataset
#change column with criteria to something new

In [56]:
#Setting new column aligns data by index
s1 = pd.Series([1,2,3,4,5,6],index=pd.date_range('20140102',periods=6))

In [57]:
s1

2014-01-02    1
2014-01-03    2
2014-01-04    3
2014-01-05    4
2014-01-06    5
2014-01-07    6
Freq: D, dtype: int64

In [58]:
tips['F'] = s1

In [59]:
tips

total_bill   tip     sex smoker   day    time  size   F
0         16.99  1.01  Female     No   Sun  Dinner     2 NaN
1         10.34  1.66    Male     No   Sun  Dinner     3 NaN
2         21.01  3.50    Male     No   Sun  Dinner     3 NaN
3         23.68  3.31    Male     No   Sun  Dinner     2 NaN
4         24.59  3.61  Female     No   Sun  Dinner     4 NaN
5         25.29  4.71    Male     No   Sun  Dinner     4 NaN
6          8.77  2.00    Male     No   Sun  Dinner     2 NaN
7         26.88  3.12    Male     No   Sun  Dinner     4 NaN
8         15.04  1.96    Male     No   Sun  Dinner     2 NaN
9         14.78  3.23    Male     No   Sun  Dinner     2 NaN
10        10.27  1.71    Male     No   Sun  Dinner     2 NaN
11        35.26  5.00  Female     No   Sun  Dinner     4 NaN
12        15.42  1.57    Male     No   Sun  Dinner     2 NaN
13        18.43  3.00    Male     No   Sun  Dinner     4 NaN
14        14.83  3.02  Female     No   Sun  Dinner     2 NaN
15        21.58  3.92    Male     No   Sun  Dinner     2 NaN
16        10.33  1.67  Female     No   Sun  Dinner     3 NaN
17        16.29  3.71    Male     No   Sun  Dinner     3 NaN
18        16.97  3.50  Female     No   Sun  Dinner     3 NaN
19        20.65  3.35    Male     No   Sat  Dinner     3 NaN
20        17.92  4.08    Male     No   Sat  Dinner     2 NaN
21        20.29  2.75  Female     No   Sat  Dinner     2 NaN
22        15.77  2.23  Female     No   Sat  Dinner     2 NaN
23        39.42  7.58    Male     No   Sat  Dinner     4 NaN
24        19.82  3.18    Male     No   Sat  Dinner     2 NaN
25        17.81  2.34    Male     No   Sat  Dinner     4 NaN
26        13.37  2.00    Male     No   Sat  Dinner     2 NaN
27        12.69  2.00    Male     No   Sat  Dinner     2 NaN
28        21.70  4.30    Male     No   Sat  Dinner     2 NaN
29        19.65  3.00  Female     No   Sat  Dinner     2 NaN
..          ...   ...     ...    ...   ...     ...   ...  ..
214       28.17  6.50  Female    Yes   Sat  Dinner     3 NaN
215       12.90  1.10  Female    Yes   Sat  Dinner     2 NaN
216       28.15  3.00    Male    Yes   Sat  Dinner     5 NaN
217       11.59  1.50    Male    Yes   Sat  Dinner     2 NaN
218        7.74  1.44    Male    Yes   Sat  Dinner     2 NaN
219       30.14  3.09  Female    Yes   Sat  Dinner     4 NaN
220       12.16  2.20    Male    Yes   Fri   Lunch     2 NaN
221       13.42  3.48  Female    Yes   Fri   Lunch     2 NaN
222        8.58  1.92    Male    Yes   Fri   Lunch     1 NaN
223       15.98  3.00  Female     No   Fri   Lunch     3 NaN
224       13.42  1.58    Male    Yes   Fri   Lunch     2 NaN
225       16.27  2.50  Female    Yes   Fri   Lunch     2 NaN
226       10.09  2.00  Female    Yes   Fri   Lunch     2 NaN
227       20.45  3.00    Male     No   Sat  Dinner     4 NaN
228       13.28  2.72    Male     No   Sat  Dinner     2 NaN
229       22.12  2.88  Female    Yes   Sat  Dinner     2 NaN
230       24.01  2.00    Male    Yes   Sat  Dinner     4 NaN
231       15.69  3.00    Male    Yes   Sat  Dinner     3 NaN
232       11.61  3.39    Male     No   Sat  Dinner     2 NaN
233       10.77  1.47    Male     No   Sat  Dinner     2 NaN
234       15.53  3.00    Male    Yes   Sat  Dinner     2 NaN
235       10.07  1.25    Male     No   Sat  Dinner     2 NaN
236       12.60  1.00    Male    Yes   Sat  Dinner     2 NaN
237       32.83  1.17    Male    Yes   Sat  Dinner     2 NaN
238       35.83  4.67  Female     No   Sat  Dinner     3 NaN
239       29.03  5.92    Male     No   Sat  Dinner     3 NaN
240       27.18  2.00  Female    Yes   Sat  Dinner     2 NaN
241       22.67  2.00    Male    Yes   Sat  Dinner     2 NaN
242       17.82  1.75    Male     No   Sat  Dinner     2 NaN
243       18.78  3.00  Female     No  Thur  Dinner     2 NaN

[244 rows x 8 columns]

### Missing Data

In [60]:
dates = pd.date_range('20140101',periods=6)
dates

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [61]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
z = pd.DataFrame(index = df.index, columns = df.columns)
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [62]:
# Add a column with missing data
df1 = df.reindex(index=dates[0:4],columns=list(df.columns) + ['E'])

In [63]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [64]:
df1

A         B         C         D    E
2014-01-01  0.447982  3.080235 -0.067153 -0.714663  1.0
2014-01-02 -0.526936 -0.308320 -1.102633 -0.943691  1.0
2014-01-03  0.629131  0.335383  0.911672  1.211076  NaN
2014-01-04 -0.311848 -0.968892 -0.193281 -0.370223  NaN

In [65]:
# find where values are null
pd.isnull(df1)

A      B      C      D      E
2014-01-01  False  False  False  False  False
2014-01-02  False  False  False  False  False
2014-01-03  False  False  False  False   True
2014-01-04  False  False  False  False   True

### Operations

In [66]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.212574  0.424042 -0.634414  0.393982
std    0.581465  1.403908  1.051119  1.213046
min   -0.526936 -0.968892 -2.010723 -0.943691
25%   -0.223152 -0.262888 -1.283932 -0.628553
50%    0.245459  0.104394 -0.647957  0.420426
75%    0.583844  0.483177 -0.098685  1.245330
max    0.994176  3.080235  0.911672  1.924643

In [67]:
df.mean(),df.mean(1) # Operation on two different axes

(A    0.212574
 B    0.424042
 C   -0.634414
 D    0.393982
 dtype: float64, 2014-01-01    0.686600
 2014-01-02   -0.720395
 2014-01-03    0.771815
 2014-01-04   -0.461061
 2014-01-05   -0.042819
 2014-01-06    0.360135
 Freq: D, dtype: float64)

In [68]:
df.head()

A         B         C         D
2014-01-01  0.447982  3.080235 -0.067153 -0.714663
2014-01-02 -0.526936 -0.308320 -1.102633 -0.943691
2014-01-03  0.629131  0.335383  0.911672  1.211076
2014-01-04 -0.311848 -0.968892 -0.193281 -0.370223
2014-01-05  0.042937 -0.126595 -1.344365  1.256748

### Applying functions

In [69]:
df

A         B         C         D
2014-01-01  0.447982  3.080235 -0.067153 -0.714663
2014-01-02 -0.526936 -0.308320 -1.102633 -0.943691
2014-01-03  0.629131  0.335383  0.911672  1.211076
2014-01-04 -0.311848 -0.968892 -0.193281 -0.370223
2014-01-05  0.042937 -0.126595 -1.344365  1.256748
2014-01-06  0.994176  0.532442 -2.010723  1.924643

In [70]:
df.apply(np.cumsum)

A         B         C         D
2014-01-01  0.447982  3.080235 -0.067153 -0.714663
2014-01-02 -0.078954  2.771916 -1.169787 -1.658354
2014-01-03  0.550177  3.107298 -0.258115 -0.447278
2014-01-04  0.238329  2.138406 -0.451396 -0.817501
2014-01-05  0.281266  2.011812 -1.795761  0.439247
2014-01-06  1.275442  2.544254 -3.806484  2.363890

In [71]:
df.apply(lambda x: x.max() - x.min())

A    1.521112
B    4.049127
C    2.922395
D    2.868334
dtype: float64

In [72]:
# Built in string methods
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

### Merge

In [ ]:
np.random.randn(10,4)

In [ ]:
#Concatenating pandas objects together
df = pd.DataFrame(np.random.randn(10,4))
df

In [ ]:
# Break it into pieces
pieces = [df[:3], df[3:7],df[7:]]
pieces

In [ ]:
pd.concat(pieces)

In [ ]:
# Also can "Join" and "Append"
df

### Grouping


In [73]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                       'foo', 'bar', 'foo', 'foo'],
                       'B' : ['one', 'one', 'two', 'three',
                             'two', 'two', 'one', 'three'],
                       'C' : np.random.randn(8),
                       'D' : np.random.randn(8)})

In [74]:
df

A      B         C         D
0  foo    one -0.140064  0.027163
1  bar    one  0.602368  1.390262
2  foo    two -0.062916  0.364195
3  bar  three  1.382763  0.561644
4  foo    two  0.270433 -0.895721
5  bar    two -0.857573  1.853142
6  foo    one -0.656835 -0.846759
7  foo  three -1.842518 -0.246481

In [75]:
df.groupby(['A','B']).sum()

C         D
A   B                        
bar one    0.602368  1.390262
    three  1.382763  0.561644
    two   -0.857573  1.853142
foo one   -0.796900 -0.819596
    three -1.842518 -0.246481
    two    0.207518 -0.531525

### Reshaping

In [76]:
# You can also stack or unstack levels

In [77]:
a = df.groupby(['A','B']).sum()

In [78]:
a

C         D
A   B                        
bar one    0.602368  1.390262
    three  1.382763  0.561644
    two   -0.857573  1.853142
foo one   -0.796900 -0.819596
    three -1.842518 -0.246481
    two    0.207518 -0.531525

In [79]:
# Pivot Tables
pd.pivot_table(df,values=['C','D'],index=['A'],columns=['B'])

C                             D                    
B         one     three       two       one     three       two
A                                                              
bar  0.602368  1.382763 -0.857573  1.390262  0.561644  1.853142
foo -0.398450 -1.842518  0.103759 -0.409798 -0.246481 -0.265763

### Time Series


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# 100 Seconds starting on January 1st
rng = pd.date_range('1/1/2014', periods=100, freq='S')

In [ ]:
# Give each second a random value
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

In [ ]:
ts

In [ ]:
# Built in resampling
ts.resample('1Min').mean() # Resample secondly to 1Minutely

In [ ]:
# Many additional time series features
ts.

### Plotting


In [ ]:
ts.plot()

In [ ]:
def randwalk(startdate,points):
    ts = pd.Series(np.random.randn(points), index=pd.date_range(startdate, periods=points))
    ts=ts.cumsum()
    ts.plot()
    return(ts)

In [ ]:
# Using pandas to make a simple random walker by repeatedly running:
a=randwalk('1/1/2012',1000)

In [ ]:
# Pandas plot function will print with labels as default

In [ ]:
df = pd.DataFrame(np.random.randn(100, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])
df = df.cumsum()
plt.figure();df.plot();plt.legend(loc='best') #

### I/O
I/O is straightforward with, for example, pd.read_csv or df.to_csv

#### The benefits of open source:

Let's look under x's in plt modules

# Next Steps

**Recommended Resources**

Name | Description
--- | ---
[Official Pandas Tutorials](http://pandas.pydata.org/pandas-docs/stable/10min.html) | Wes & Company's selection of tutorials and lectures
[Julia Evans Pandas Cookbook](https://github.com/jvns/pandas-cookbook) | Great resource with examples from weather, bikes and 311 calls
[Learn Pandas Tutorials](https://bitbucket.org/hrojas/learn-pandas) | A great series of Pandas tutorials from Dave Rojas
[Research Computing Python Data PYNBs](https://github.com/ResearchComputing/Meetup-Fall-2013/tree/master/python) | A super awesome set of python notebooks from a meetup-based course exclusively devoted to pandas